spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jkvishwakarma717@gmail.com
    password: cpslvyqoduzeshxi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


